/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rockpaperscissor;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Subriti
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    String comp;
    String user;
    static int Your_win = 0;
    static int Comp_win = 0;
    static int Tie = 0;

    public GUI() {
        initComponents();
        userPanel.setVisible(true);
        compPanel.setVisible(true);
        jPanel3.setVisible(true);

        userDefault.setVisible(true);
        compDefault.setVisible(true);

        userRock.setVisible(false);
        userScissor.setVisible(false);
        compScissor.setVisible(false);
        compRock.setVisible(false);
        userPaper.setVisible(false);
        compPaper.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userDefault = new javax.swing.JLabel();
        userRock = new javax.swing.JLabel();
        userScissor = new javax.swing.JLabel();
        rockButton = new javax.swing.JButton();
        paperButton = new javax.swing.JButton();
        scissorButton = new javax.swing.JButton();
        userPaper = new javax.swing.JLabel();
        compPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        compDefault = new javax.swing.JLabel();
        compScissor = new javax.swing.JLabel();
        compRock = new javax.swing.JLabel();
        compPaper = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        userScore = new javax.swing.JLabel();
        compScore = new javax.swing.JLabel();
        tieScore = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rock Paper Scissor");
        setBackground(new java.awt.Color(255, 153, 153));
        setLocation(new java.awt.Point(420, 200));
        setResizable(false);

        userPanel.setBackground(new java.awt.Color(61, 183, 228));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("You");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        userDefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/You_Default.png"))); // NOI18N
        userDefault.setMaximumSize(new java.awt.Dimension(474, 368));
        userDefault.setMinimumSize(new java.awt.Dimension(474, 368));
        userDefault.setPreferredSize(new java.awt.Dimension(474, 368));

        userRock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/You_Rock.png"))); // NOI18N

        userScissor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/You_Scissor.png"))); // NOI18N

        rockButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rockButton.setText("Rock");
        rockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockButtonActionPerformed(evt);
            }
        });

        paperButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        paperButton.setText("Paper");
        paperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperButtonActionPerformed(evt);
            }
        });

        scissorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        scissorButton.setText("Scissor");
        scissorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scissorButtonActionPerformed(evt);
            }
        });

        userPaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Paper.png"))); // NOI18N

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(userDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userRock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userScissor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rockButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paperButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scissorButton))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(userRock, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userScissor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userPaper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rockButton)
                    .addComponent(scissorButton)
                    .addComponent(paperButton))
                .addContainerGap())
        );

        compPanel.setBackground(new java.awt.Color(253, 136, 73));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Computer");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        compDefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Comp_Default.png"))); // NOI18N
        compDefault.setToolTipText("");
        compDefault.setMaximumSize(new java.awt.Dimension(474, 368));
        compDefault.setMinimumSize(new java.awt.Dimension(474, 368));
        compDefault.setPreferredSize(new java.awt.Dimension(474, 368));

        compScissor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Comp_Scissor.png"))); // NOI18N

        compRock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Comp_Rock.png"))); // NOI18N

        compPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Paper.png"))); // NOI18N

        javax.swing.GroupLayout compPanelLayout = new javax.swing.GroupLayout(compPanel);
        compPanel.setLayout(compPanelLayout);
        compPanelLayout.setHorizontalGroup(
            compPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compPanelLayout.createSequentialGroup()
                .addGroup(compPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(compPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2))
                    .addGroup(compPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(compDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compRock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compPaper)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compScissor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        compPanelLayout.setVerticalGroup(
            compPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(compPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compScissor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compPaper)
                    .addComponent(compRock, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(407, 407, 407))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Result");

        jPanel1.setBackground(new java.awt.Color(255, 102, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Ties: ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Your Score: ");

        userScore.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userScore.setText("0");

        compScore.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        compScore.setText("0");

        tieScore.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tieScore.setText("0");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Computer's Score: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userScore, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compScore, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tieScore, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(userScore, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compScore, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(tieScore, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(compPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(compPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scissorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scissorButtonActionPerformed
        // TODO add your handling code here:
        userScissor.setVisible(true);
        userPaper.setVisible(false);
        userDefault.setVisible(false);
        userRock.setVisible(false);

        user = "Scissor";
        comp = generateCompMove();

        if (comp == "Rock") {
            getRockImage();
            getCompWinsMsg();
        } else if (comp == "Scissor") {
            getScissorImage();
            getTieMsg();
        } else if (comp == "Paper") {
            getPaperImage();
            getUserWinsMsg();
        }
        showWinningMessage();
    }//GEN-LAST:event_scissorButtonActionPerformed

    private void rockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockButtonActionPerformed
        // TODO add your handling code here:
        userDefault.setVisible(false);
        userScissor.setVisible(false);
        userPaper.setVisible(false);
        userRock.setVisible(true);

        user = "Rock";
        comp = generateCompMove();

        if (comp == "Rock") {
            getRockImage();
            getTieMsg();
        } else if (comp == "Scissor") {
            getScissorImage();
            getUserWinsMsg();
        } else if (comp == "Paper") {
            getPaperImage();
            getCompWinsMsg();
        }
        showWinningMessage();
    }//GEN-LAST:event_rockButtonActionPerformed

    private void paperButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperButtonActionPerformed
        // TODO add your handling code here:
        userPaper.setVisible(true);
        userDefault.setVisible(false);
        userRock.setVisible(false);
        userScissor.setVisible(false);

        user = "Paper";
        comp = generateCompMove();

        if (comp == "Rock") {
            getRockImage();
            getUserWinsMsg();
        } else if (comp == "Scissor") {
            getScissorImage();
            getCompWinsMsg();
        } else if (comp == "Paper") {
            getPaperImage();
            getTieMsg();
        }
        showWinningMessage();
    }//GEN-LAST:event_paperButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel compDefault;
    private javax.swing.JPanel compPanel;
    private javax.swing.JLabel compPaper;
    private javax.swing.JLabel compRock;
    private javax.swing.JLabel compScissor;
    private javax.swing.JLabel compScore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton paperButton;
    private javax.swing.JButton rockButton;
    private javax.swing.JButton scissorButton;
    private javax.swing.JLabel tieScore;
    private javax.swing.JLabel userDefault;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel userPaper;
    private javax.swing.JLabel userRock;
    private javax.swing.JLabel userScissor;
    private javax.swing.JLabel userScore;
    // End of variables declaration//GEN-END:variables

    private String generateCompMove() {
        Random rand = new Random();
        // Generate random integers in range 0 to 2
        int random = rand.nextInt(3);
        switch (random) {
            case 0 -> {
                return "Rock";
            }
            case 1 -> {
                return "Paper";
            }
            case 2 -> {
                return "Scissor";
            }
            default -> {
            }
        }
        return null;
    }

    private void showWinningMessage() {
        if (Your_win == 10) {
            JOptionPane.showMessageDialog(rootPane, "Game Finished: YOU WON");
            System.out.println("Game Finished: YOU WON");
            System.exit(0);
        } else if (Comp_win == 10) {
            JOptionPane.showMessageDialog(rootPane, "Game Finished: COMPUTER WON");
            System.out.println("Game Finished: COMPUTER WON");
            System.exit(0);
        } else if (Tie == 10) {
            JOptionPane.showMessageDialog(rootPane, "Game Finished: TIE");
            System.out.println("Game Finished: TIE");
            System.exit(0);
        }
    }

    private void getRockImage() {
        compRock.setVisible(true);
        compDefault.setVisible(false);
        compScissor.setVisible(false);
        compPaper.setVisible(false);
    }

    private void getScissorImage() {
        compRock.setVisible(false);
        compDefault.setVisible(false);
        compScissor.setVisible(true);
        compPaper.setVisible(false);
    }

    private void getPaperImage() {
        compRock.setVisible(false);
        compDefault.setVisible(false);
        compScissor.setVisible(false);
        compPaper.setVisible(true);
    }

    private void getCompWinsMsg() {
        jLabel4.setText("Computer Wins !!");
        Comp_win += 1;
        String cwin = Integer.toString(Comp_win);
        compScore.setText(cwin);
    }

    private void getTieMsg() {
        jLabel4.setText("Tie !!");
        Tie += 1;
        String tie = Integer.toString(Tie);
        tieScore.setText(tie);
    }

    private void getUserWinsMsg() {
        jLabel4.setText("You Win !!");
        Your_win += 1;
        String ywin = Integer.toString(Your_win);
        userScore.setText(ywin);
    }
}
